// src/redux/types.js
// Add these to your existing types file

// Roles action types
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAIL = "FETCH_ROLES_FAIL";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
export const GENERATE_DESCRIPTION_SUCCESS = "GENERATE_DESCRIPTION_SUCCESS";
export const GENERATE_DESCRIPTION_FAIL = "GENERATE_DESCRIPTION_FAIL";